/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/js/curry.js');

// tslint:disable-next-line:no-var-requires
const DemoBS = require('./Demo.bs');

// tslint:disable-next-line:max-classes-per-file 
// tslint:disable-next-line:class-name
export abstract class operation { protected opaque!: any }; /* simulate opaque types */

export const calc: (_1:operation) => number = DemoBS.calc;

export const myint: (_1:number) => operation = DemoBS.myint;

export const add: (_1:operation, _2:operation) => operation = function _(Arg1: any, Arg2: any) {
  const result = Curry._2(DemoBS.add, Arg1, Arg2);
  return result
};

export const sum: (_1:operation, _2:operation) => operation = function _(Arg1: any, Arg2: any) {
  const result = Curry._2(DemoBS.sum, Arg1, Arg2);
  return result
};
