// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function calc(operation) {
  switch (operation.tag | 0) {
    case 0 : 
        return calc(operation[0]) + calc(operation[1]) | 0;
    case 1 : 
        return Caml_int32.imul(calc(operation[0]), calc(operation[1]));
    case 2 : 
        return operation[0];
    
  }
}

function myint(i) {
  return /* Int */Block.__(2, [i]);
}

function add(x, y) {
  return /* Add */Block.__(0, [
            x,
            y
          ]);
}

function sum(x, y) {
  return /* Sum */Block.__(1, [
            x,
            y
          ]);
}

exports.calc = calc;
exports.myint = myint;
exports.add = add;
exports.sum = sum;
/* No side effect */
