// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function greeting(person) {
  if (typeof person === "number") {
    if (person !== 0) {
      return "Hello Director.";
    } else {
      return "Hey Professor!";
    }
  } else {
    var anyOtherName = person[0];
    if (anyOtherName === "Richard") {
      return "Still here Ricky?";
    } else {
      return "Hey, " + (anyOtherName + ".");
    }
  }
}

function calc(operation) {
  switch (operation.tag | 0) {
    case 0 : 
        return calc(operation[0]) + calc(operation[1]) | 0;
    case 1 : 
        return Caml_int32.imul(calc(operation[0]), calc(operation[1]));
    case 2 : 
        return operation[0];
    
  }
}

exports.greeting = greeting;
exports.calc = calc;
/* No side effect */
